name: Master Branch

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Compile CV Phaser 3 Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '13'
      - run: npm install
      - run: npm run build
  